export enum UserClassEnum {
  EXTERN = 'EXTERN',
  PROF = 'PROF',
  AUTO_1A = 'AUTO_1A',
  AUTO_2A = 'AUTO_2A',
  AUTO_3A = 'AUTO_3A',
  INFO_1A = 'INFO_1A',
  INFO_2A = 'INFO_2A',
  INFO_3A = 'INFO_3A',
  MECA_1A = 'MECA_1A',
  MECA_2A = 'MECA_2A',
  MECA_3A = 'MECA_3A',
  TEXT_1A = 'TEXT_1A',
  TEXT_2A = 'TEXT_2A',
  TEXT_3A = 'TEXT_3A',
  GI_1A = 'GI_1A',
  GI_2A = 'GI_2A',
  GI_3A = 'GI_3A',
  OLD_4A = 'OLD_4A',
}
